customerinventory/customerinventory/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^', include("inventory.urls", namespace="inventory")),
    url(r'^admin/', include(admin.site.urls)),
]

customerinventory/inventory/urls.py
from django.conf.urls import url, include
from .views import (index,item_detail)
# from . import views as post_views
# using post_views.post_update

urlpatterns = [
    url(r'^$', index, name="index"),
    url(r'^item/(?P<id>\d+)/', item_detail, name="item_detail"),
]

customerinventory/inventory/models.py
from django.db import models

# Create your models here.


class Item(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    amount = models.IntegerField(default=1)

    def __str__(self):
        return self.title

customerinventory/inventory/views.py
from django.shortcuts import render
from django.http import Http404
from django.http import HttpResponse

from .models import Item


def index(request):
    items = Item.objects.exclude(amount=0)
    context = {
        "items": items
    }
    return render(request, 'inventory/index.html', context)


def item_detail(request, id):
    try:
        item = Item.objects.get(id=id)
    except Item.DoesNotExist:
        raise Http404("This item does not exist")

    context = {
        "item": item
    }
    return render(request, 'inventory/items_details.html', context)

customerinventory/templates/base.html
{% load staticfiles %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Inventory</title>
    <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'main.css'%}">
</head>
<body>

{%block content%}

{% endblock %}
<script src="{% static 'test.js' %}"></script>

<script
  src="http://code.jquery.com/jquery-3.2.1.slim.min.js"
  integrity="sha256-k2WSCIexGzOj3Euiig+TlR8gA0EmPjuc79OEeY5L45g="
  crossorigin="anonymous"></script>

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</body>
</html>

customerinventory/templates/inventory/index.html
{% extends '../base.html' %}

{% block content %}

<h2>Items list</h2>

    {%for item in items %}
        <p><a href="{% url 'inventory:item_detail' item.id %}">{{item.title|capfirst}}</a></p>
        <p>{{item.description}}</p>
        <p>{{item.amount}}</p>

    {% endfor %}

{% endblock %}

customerinventory/templates/inventory/items_details.html
{% extends '../base.html' %}

{% block content %}

    <h2>Items Details</h2>

    <p><a href="{% url 'inventory:index' %}">Back </a></p>
    <p>{{item.title}}</p>
    <p>{{item.description}}</p>
    <p>{{item.amount}}</p>

{% endblock %}